In [1]:
import torch

In [2]:
matrix = torch.randint(10,40,(2,3))
matrix

tensor([[38, 28, 19],
        [12, 36, 35]])

In [8]:
matrix.dtype

torch.int64

In [ ]:
# toplama
# cıkartma
# carpma
# bolme
# kuvvet alma
# cebirsel çarpım
# matrix  toplama
# matrix cıkartma
# matrix carpma
# matrix bolme

In [3]:
skaler_toplama = matrix + 10
skaler_toplama

tensor([[48, 38, 29],
        [22, 46, 45]])

In [4]:
skaler_cikartma = matrix -10
skaler_cikartma

tensor([[28, 18,  9],
        [ 2, 26, 25]])

In [5]:
skaler_carpma = matrix * 5
skaler_carpma

tensor([[190, 140,  95],
        [ 60, 180, 175]])

In [7]:
skaler_bolme = matrix / 2
skaler_bolme, skaler_bolme.dtype

(tensor([[19.0000, 14.0000,  9.5000],
         [ 6.0000, 18.0000, 17.5000]]),
 torch.float32)

In [11]:
skaler_ustel = matrix ** 2
skaler_ustel

tensor([[1444,  784,  361],
        [ 144, 1296, 1225]])

### Tensörler Arası İşlemler

In [12]:
matrix2 = torch.randint(1,10,(2,3))
matrix2, matrix

(tensor([[1, 1, 5],
         [2, 4, 3]]),
 tensor([[38, 28, 19],
         [12, 36, 35]]))

In [14]:
tensor_toplama = matrix+matrix2 
tensor_toplama

tensor([[39, 29, 24],
        [14, 40, 38]])

In [16]:
tensor_toplama = torch.add(matrix, matrix2)
tensor_toplama

tensor([[39, 29, 24],
        [14, 40, 38]])

In [17]:
tensor_cikarma = matrix - matrix2
tensor_cikarma

tensor([[37, 27, 14],
        [10, 32, 32]])

In [18]:
tensro_cikarma = torch.sub(matrix, matrix2)
tensor_cikarma

tensor([[37, 27, 14],
        [10, 32, 32]])

In [20]:
matrix2, matrix

(tensor([[1, 1, 5],
         [2, 4, 3]]),
 tensor([[38, 28, 19],
         [12, 36, 35]]))

In [19]:
tensor_carpma = matrix * matrix2
tensor_carpma

tensor([[ 38,  28,  95],
        [ 24, 144, 105]])

In [21]:
tensor_carpma = torch.mul(matrix, matrix2)
tensor_carpma

tensor([[ 38,  28,  95],
        [ 24, 144, 105]])

boyut (2,3) * (3,2)

In [25]:
matrix 

tensor([[38, 28, 19],
        [12, 36, 35]])

In [22]:
matrix2.T

tensor([[1, 2],
        [1, 4],
        [5, 3]])

In [24]:
cebirsel_carpma = torch.matmul(matrix, matrix2.T)
cebirsel_carpma

tensor([[161, 245],
        [223, 273]])

In [27]:
cebirsel_carpma = matrix @ matrix2.T
cebirsel_carpma

tensor([[161, 245],
        [223, 273]])

In [29]:
matrix, matrix2

(tensor([[38, 28, 19],
         [12, 36, 35]]),
 tensor([[1, 1, 5],
         [2, 4, 3]]))

In [ ]:
tensor_bolme = matrix / matrix2
tensor_bolme

tensor([[38.0000, 28.0000,  3.8000],
        [ 6.0000,  9.0000, 11.6667]])

In [30]:
tensor_bolme = torch.div(matrix, matrix2)
tensor_bolme

tensor([[38.0000, 28.0000,  3.8000],
        [ 6.0000,  9.0000, 11.6667]])